### ISSUE TITLE
Possible new contributors ??

### ISSUE THREAD

**Issue by AzaleeX** [PocketMine-School/Pocketmine-School#86]
Hello, I would like to enter your pocketmine school project to translate the pages of the help site into any language, but also to add categories as an instance in the main class (PluginBase) and many others.

 thank you for reading my message

**Comment by Zaelee** [comment]
![image](https://user-images.githubusercontent.com/82237910/200162941-165f5e1b-12ca-46b1-962c-e6513b8f151b.png)

add this
